#print(5+3)
#print (2**3)
#print(10-2)
#print(16 / 2)
#favourite_number='10'
#message = "my favorite number is "  +  str(favourite_number)
#print(message)
Tourist_destination=[ 'France','Rome','Morocco','Isreal','Jerusalem' ]
print("\n list in original format")
print(Tourist_destination)
print("\nlist in alphabetical order without modifying actual list")
print(sorted(Tourist_destination))
#Tourist_destination.sort()
#print(Tourist_destination)
print("\nlist in reverse alphabetical order without modifying actual order oflist")
#Tourist_destination.reverse(True)
print(sorted(Tourist_destination, reverse=True ))
print("\n list in original order")
print(Tourist_destination)
print("\n using reverse to change the order of the list")
Tourist_destination.reverse()
print(Tourist_destination)
print("\n using sort to store list in aphabetical order")
Tourist_destination.sort()
print(Tourist_destination)
print("\n save list in sorted alphabetical order")
Tourist_destination.sort(reverse=True)
print(Tourist_destination)


#Tourist_destination.sort(reverse=True)
#print(sorted(Tourist_destination))
#Tourist_destination.reverse()
#Tourist_destination.sort()
#print(Tourist_destination)
#Tourist_destination(sortedreverse=True(Tourist_destination))
#Tourist_destination.sort(reverse=True)
#print(sorted(Tourist_destination))